### ISSUE TITLE
PHP Warnings when a category with no sub-cats is chosen from the dropdown

### ISSUE THREAD

**Issue by scottcwilson** [lat9/printable_price_list#31]
As reported in https://www.zen-cart.com/showthread.php?49126-Printable-Price-list-support-thread&p=1401414#post1401414 

```
[22-Jun-2024 15:33:49 America/Anchorage] Request URI: /store/index.php?main_page=pricelist&plCat=13&profile=1&language=en, IP address: 66.249.79.32, Language id 1
#0 /home/client/public_html/store/zc_plugins/PrintablePriceList/v4.0.0/catalog/includes/templates/default/templates/tpl_pricelist_default.php(167): zen_debug_error_handler()
#1 /home/client/public_html/store/includes/templates/bootstrap/common/tpl_main_page.php(220): require('/home/client/...')
#2 /home/client/public_html/store/index.php(94): require('/home/client/...')
--> PHP Warning: Undefined array key "is_product" in /home/client/public_html/store/zc_plugins/PrintablePriceList/v4.0.0/catalog/includes/templates/default/templates/tpl_pricelist_default.php on line 167.

[22-Jun-2024 15:33:49 America/Anchorage] Request URI: /store/index.php?main_page=pricelist&plCat=13&profile=1&language=en, IP address: 66.249.79.32, Language id 1
#0 /home/client/public_html/store/zc_plugins/PrintablePriceList/v4.0.0/catalog/includes/templates/default/templates/tpl_pricelist_default.php(170): zen_debug_error_handler()
#1 /home/client/public_html/store/includes/templates/bootstrap/common/tpl_main_page.php(220): require('/home/client/...')
#2 /home/client/public_html/store/index.php(94): require('/home/client/...')
--> PHP Warning: Undefined array key "level" in /home/client/public_html/store/zc_plugins/PrintablePriceList/v4.0.0/catalog/includes/templates/default/templates/tpl_pricelist_default.php on line 170.

[22-Jun-2024 15:33:49 America/Anchorage] Request URI: /store/index.php?main_page=pricelist&plCat=13&profile=1&language=en, IP address: 66.249.79.32, Language id 1
#0 /home/client/public_html/store/zc_plugins/PrintablePriceList/v4.0.0/catalog/includes/templates/default/templates/tpl_pricelist_default.php(172): zen_debug_error_handler()
#1 /home/client/public_html/store/includes/templates/bootstrap/common/tpl_main_page.php(220): require('/home/client/...')
#2 /home/client/public_html/store/index.php(94): require('/home/client/...')
--> PHP Warning: Undefined array key "categories_name" in /home/client/public_html/store/zc_plugins/PrintablePriceList/v4.0.0/catalog/includes/templates/default/templates/tpl_pricelist_default.php on line 172.

[22-Jun-2024 15:33:49 America/Anchorage] Request URI: /store/index.php?main_page=pricelist&plCat=13&profile=1&language=en, IP address: 66.249.79.32, Language id 1
#0 /home/client/public_html/store/zc_plugins/PrintablePriceList/v4.0.0/catalog/includes/templates/default/templates/tpl_pricelist_default.php(177): zen_debug_error_handler()
#1 /home/client/public_html/store/includes/templates/bootstrap/common/tpl_main_page.php(220): require('/home/client/...')
#2 /home/client/public_html/store/index.php(94): require('/home/client/...')
--> PHP Warning: Undefined array key "level" in /home/client/public_html/store/zc_plugins/PrintablePriceList/v4.0.0/catalog/includes/templates/default/templates/tpl_pricelist_default.php on line 177.

```

**Comment by lat9** [comment]
A screenshot of that profile's configuration would help me determine the root-cause of this issue.

**Comment by scottcwilson** [comment]
<img width="1026" alt="profile1" src="https://github.com/lat9/printable_price_list/assets/4391638/944044cf-67da-4539-ba24-f14fd524e4a9">

**Comment by lat9** [comment]
Reproduced with default settings and demo products; just choose the "Gift Certificates" category to view.
